# Generated by Django 2.2.12 on 2020-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
