# Generated by Django 2.2.12 on 2020-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_staticpage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
