# Generated by Django 2.2.9 on 2020-05-23 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Lpa',
            fields=[
                ('lpa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lpa_name', models.CharField(max_length=99)),
                ('LAD19CD', models.CharField(blank=True, max_length=15)),
                ('LAD19NM', models.CharField(blank=True, max_length=99)),
                ('lpa_text', models.CharField(blank=True, max_length=200)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planfinder.County')),
            ],
        ),
        migrations.CreateModel(
            name='NationalPark',
            fields=[
                ('natpark_id', models.IntegerField(primary_key=True, serialize=False)),
                ('natpark_name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='NeighbourhoodPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_url', models.URLField()),
                ('map_location', models.CharField(max_length=200)),
                ('ref_date', models.DateField(blank=True, null=True, verbose_name='referendum date')),
                ('supersededDate', models.DateField(blank=True, null=True, verbose_name='date superseded by new plan')),
                ('supersededBy_desc', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('cross_authority_plan', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('lpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planfinder.Lpa')),
                ('natpark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planfinder.NationalPark')),
            ],
        ),
    ]
