# Generated by Django 2.2.9 on 2020-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_name',
            field=models.CharField(max_length=99, verbose_name='Counties'),
        ),
        migrations.AlterField(
            model_name='lpa',
            name='lpa_name',
            field=models.CharField(max_length=99, verbose_name='LPAs'),
        ),
    ]
