# Generated by Django 2.2.9 on 2020-05-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planfinder', '0002_auto_20200523_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='lpa',
            options={'verbose_name': 'Local Planning Authority', 'verbose_name_plural': 'Local Planning Authorities'},
        ),
        migrations.AlterField(
            model_name='county',
            name='county_name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='lpa',
            name='lpa_name',
            field=models.CharField(max_length=99),
        ),
    ]
