# Generated by Django 2.2.12 on 2020-06-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planfinder', '0003_auto_20200523_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhoodplan',
            name='supersededBy_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planfinder.NeighbourhoodPlan'),
        ),
    ]
