# Generated by Django 2.2.12 on 2020-06-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='LocalAuthorityLHN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la_code', models.CharField(default='', max_length=99)),
                ('la_area', models.CharField(max_length=99)),
                ('hp_2018', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2019', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2020', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2021', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2022', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2023', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2024', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2025', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2026', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2027', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2028', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2029', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2030', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2031', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2032', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2033', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2034', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2035', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2036', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2037', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2038', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('hp_2039', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('med_aff_rat_2017', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('med_aff_rat_2018', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('med_aff_rat_2019', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lhn.County')),
            ],
            options={
                'verbose_name': 'Local Authority area',
                'verbose_name_plural': 'Local Authority areas',
                'ordering': ['la_area'],
            },
        ),
    ]
